"""empty message

Revision ID: 1037c34cfdb0
Revises: 2b1a26d22d97
Create Date: 2015-01-16 12:29:12.669874

"""

# revision identifiers, used by Alembic.
revision = '1037c34cfdb0'
down_revision = '2b1a26d22d97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
