"""empty message

Revision ID: 11ac0ab909ac
Revises: 1d3c6f332c70
Create Date: 2015-01-13 16:22:57.780122

"""

# revision identifiers, used by Alembic.
revision = '11ac0ab909ac'
down_revision = '1d3c6f332c70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
