"""empty message

Revision ID: 13079e2c6414
Revises: 2374e7061e2b
Create Date: 2015-01-05 13:39:19.953943

"""

# revision identifiers, used by Alembic.
revision = '13079e2c6414'
down_revision = '2374e7061e2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
