"""empty message

Revision ID: 13f4431f940b
Revises: 34979e2587eb
Create Date: 2015-01-15 11:04:45.135478

"""

# revision identifiers, used by Alembic.
revision = '13f4431f940b'
down_revision = '34979e2587eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
