"""empty message

Revision ID: 162f97cc232f
Revises: 504f78fc2e9c
Create Date: 2015-01-15 11:36:11.847548

"""

# revision identifiers, used by Alembic.
revision = '162f97cc232f'
down_revision = '504f78fc2e9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
