"""empty message

Revision ID: 181e50d0f8ac
Revises: 4cef94517f8b
Create Date: 2014-12-16 13:23:59.244368

"""

# revision identifiers, used by Alembic.
revision = '181e50d0f8ac'
down_revision = '4cef94517f8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
