"""empty message

Revision ID: 19b6229b1977
Revises: 1b4fd212d518
Create Date: 2015-01-14 14:44:37.808196

"""

# revision identifiers, used by Alembic.
revision = '19b6229b1977'
down_revision = '1b4fd212d518'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
