"""empty message

Revision ID: 1b0f8cbcd662
Revises: 181e50d0f8ac
Create Date: 2015-01-05 10:58:38.173920

"""

# revision identifiers, used by Alembic.
revision = '1b0f8cbcd662'
down_revision = '181e50d0f8ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('urlname', sa.String(length=100), nullable=True),
    sa.Column('full_title', sa.String(length=300), nullable=True),
    sa.Column('brief_synopsis', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('twitter', sa.String(length=64), nullable=True),
    sa.Column('facebook', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publications_timestamp', 'publications', ['timestamp'], unique=False)
    op.create_table('copubauthors',
    sa.Column('user_name', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copubauthors')
    op.drop_index('ix_publications_timestamp', 'publications')
    op.drop_table('publications')
    ### end Alembic commands ###
