"""empty message

Revision ID: 1b4fd212d518
Revises: fc0c122460a
Create Date: 2015-01-14 14:40:54.243642

"""

# revision identifiers, used by Alembic.
revision = '1b4fd212d518'
down_revision = 'fc0c122460a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('twitter_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('twitter_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_name')
    op.drop_column('projects', 'twitter_name')
    ### end Alembic commands ###
