"""empty message

Revision ID: 1d3c6f332c70
Revises: 4e27891a33fc
Create Date: 2015-01-13 16:18:10.520385

"""

# revision identifiers, used by Alembic.
revision = '1d3c6f332c70'
down_revision = '4e27891a33fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
