"""empty message

Revision ID: 1e0293539f8c
Revises: 3ffd3c95d96d
Create Date: 2015-01-13 14:57:21.669303

"""

# revision identifiers, used by Alembic.
revision = '1e0293539f8c'
down_revision = '3ffd3c95d96d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
