"""empty message

Revision ID: 1e41fe4b4374
Revises: 10d829d3a353
Create Date: 2015-03-02 09:29:35.514464

"""

# revision identifiers, used by Alembic.
revision = '1e41fe4b4374'
down_revision = '10d829d3a353'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_2', 'species', [u'id'], unique=False)
    op.create_index('fkplantspecies', 'plant', [u'species_id'], unique=False)
    ### end Alembic commands ###
