"""empty message

Revision ID: 1f37c82f0e16
Revises: 1dbe283c483
Create Date: 2015-02-03 14:45:32.652692

"""

# revision identifiers, used by Alembic.
revision = '1f37c82f0e16'
down_revision = '1dbe283c483'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
