"""empty message

Revision ID: 20b81e208dc4
Revises: d2568053d8e
Create Date: 2015-01-15 09:45:48.396153

"""

# revision identifiers, used by Alembic.
revision = '20b81e208dc4'
down_revision = 'd2568053d8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
