"""empty message

Revision ID: 2374e7061e2b
Revises: 5ae3430a492b
Create Date: 2015-01-05 13:33:09.903142

"""

# revision identifiers, used by Alembic.
revision = '2374e7061e2b'
down_revision = '5ae3430a492b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
