"""empty message

Revision ID: 248b1e88a76d
Revises: 421a3474d3e
Create Date: 2015-01-05 13:44:27.142404

"""

# revision identifiers, used by Alembic.
revision = '248b1e88a76d'
down_revision = '421a3474d3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
