"""empty message

Revision ID: 29fa5a9b9555
Revises: 9eb226546f
Create Date: 2015-01-16 12:30:20.075802

"""

# revision identifiers, used by Alembic.
revision = '29fa5a9b9555'
down_revision = '9eb226546f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
