"""empty message

Revision ID: 2b055212ffb5
Revises: 4ae7938fac71
Create Date: 2015-01-14 17:49:21.664475

"""

# revision identifiers, used by Alembic.
revision = '2b055212ffb5'
down_revision = '4ae7938fac71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
