"""empty message

Revision ID: 2b1a26d22d97
Revises: 573899ac4699
Create Date: 2015-01-15 16:02:37.983359

"""

# revision identifiers, used by Alembic.
revision = '2b1a26d22d97'
down_revision = '573899ac4699'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
