"""empty message

Revision ID: 2c8d61c4f624
Revises: 4d289f3a6088
Create Date: 2015-01-14 15:28:09.455939

"""

# revision identifiers, used by Alembic.
revision = '2c8d61c4f624'
down_revision = '4d289f3a6088'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('other_researchers', sa.String(length=100), nullable=True))
    op.add_column('publications', sa.Column('other_researchers', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'other_researchers')
    op.drop_column('projects', 'other_researchers')
    ### end Alembic commands ###
