"""empty message

Revision ID: 2fed564a5b0d
Revises: 2c8d61c4f624
Create Date: 2015-01-14 15:28:31.667263

"""

# revision identifiers, used by Alembic.
revision = '2fed564a5b0d'
down_revision = '2c8d61c4f624'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
