"""empty message

Revision ID: 308c63fe16be
Revises: 1b0f8cbcd662
Create Date: 2015-01-05 11:18:22.009107

"""

# revision identifiers, used by Alembic.
revision = '308c63fe16be'
down_revision = '1b0f8cbcd662'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('citation', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'citation')
    ### end Alembic commands ###
