"""empty message

Revision ID: 343acd11e95e
Revises: 162f97cc232f
Create Date: 2015-01-15 11:41:42.345341

"""

# revision identifiers, used by Alembic.
revision = '343acd11e95e'
down_revision = '162f97cc232f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('synopsis_html', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('synopsis_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'synopsis_html')
    op.drop_column('projects', 'synopsis_html')
    ### end Alembic commands ###
