"""empty message

Revision ID: 348eb6cc6b34
Revises: 1f37c82f0e16
Create Date: 2015-02-05 14:46:50.645431

"""

# revision identifiers, used by Alembic.
revision = '348eb6cc6b34'
down_revision = '1f37c82f0e16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
#    op.drop_index('plantspecies', 'plant')
    op.add_column('species', sa.Column('localimageurl', sa.String(length=64), nullable=True))
    op.add_column('species', sa.Column('originalpageurl', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'originalpageurl')
    op.drop_column('species', 'localimageurl')
    op.create_index('plantspecies', 'plant', [u'species_id'], unique=False)
    ### end Alembic commands ###
