"""empty message

Revision ID: 349210aa9b31
Revises: 308c63fe16be
Create Date: 2015-01-05 11:32:02.610387

"""

# revision identifiers, used by Alembic.
revision = '349210aa9b31'
down_revision = '308c63fe16be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
