"""empty message

Revision ID: 34979e2587eb
Revises: 20b81e208dc4
Create Date: 2015-01-15 10:34:56.515202

"""

# revision identifiers, used by Alembic.
revision = '34979e2587eb'
down_revision = '20b81e208dc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
