"""empty message

Revision ID: 354700e006cf
Revises: 477a33bdedb9
Create Date: 2014-11-18 09:34:18.042819

"""

# revision identifiers, used by Alembic.
revision = '354700e006cf'
down_revision = '477a33bdedb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
