"""empty message

Revision ID: 3577679d61a0
Revises: 343acd11e95e
Create Date: 2015-01-15 11:42:21.311945

"""

# revision identifiers, used by Alembic.
revision = '3577679d61a0'
down_revision = '343acd11e95e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
