"""empty message

Revision ID: 369287a0c43b
Revises: 47a48d9528c6
Create Date: 2015-01-15 12:46:22.242913

"""

# revision identifiers, used by Alembic.
revision = '369287a0c43b'
down_revision = '47a48d9528c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('publications', sa.Column('status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'status')
    op.drop_column('projects', 'status')
    ### end Alembic commands ###
