"""empty message

Revision ID: 3d6720c9c8a5
Revises: 4f4b27fea9c4
Create Date: 2015-01-05 13:09:08.500871

"""

# revision identifiers, used by Alembic.
revision = '3d6720c9c8a5'
down_revision = '4f4b27fea9c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
