"""empty message

Revision ID: 3fc0efb94fd8
Revises: None
Create Date: 2015-01-07 13:54:11.831950

"""

# revision identifiers, used by Alembic.
revision = '3fc0efb94fd8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('quals', sa.Text(), nullable=True),
    sa.Column('jobtitle', sa.String(length=64), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('pub_email', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.Column('twitter', sa.String(length=64), nullable=True),
    sa.Column('linkedin', sa.String(length=64), nullable=True),
    sa.Column('google', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('urlname', sa.String(length=100), nullable=True),
    sa.Column('full_title', sa.String(length=300), nullable=True),
    sa.Column('brief_synopsis', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('twitter', sa.String(length=64), nullable=True),
    sa.Column('facebook', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urlname')
    )
    op.create_index('ix_projects_timestamp', 'projects', ['timestamp'], unique=False)
    op.create_table('coauthors',
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], )
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('urlname', sa.String(length=100), nullable=True),
    sa.Column('full_title', sa.String(length=300), nullable=True),
    sa.Column('brief_synopsis', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('twitter', sa.String(length=64), nullable=True),
    sa.Column('facebook', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['roles.name'], ),
    sa.ForeignKeyConstraint(['project_name'], ['projects.urlname'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publications_timestamp', 'publications', ['timestamp'], unique=False)
    op.create_table('copubauthors',
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copubauthors')
    op.drop_index('ix_publications_timestamp', 'publications')
    op.drop_table('publications')
    op.drop_table('coauthors')
    op.drop_index('ix_projects_timestamp', 'projects')
    op.drop_table('projects')
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    op.drop_index('ix_roles_default', 'roles')
    op.drop_table('roles')
    ### end Alembic commands ###
