"""empty message

Revision ID: 40c5c95b2a43
Revises: 3577679d61a0
Create Date: 2015-01-15 12:15:02.024040

"""

# revision identifiers, used by Alembic.
revision = '40c5c95b2a43'
down_revision = '3577679d61a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quals_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quals_html')
    ### end Alembic commands ###
