"""empty message

Revision ID: 418b3ff1c47
Revises: 29fa5a9b9555
Create Date: 2015-01-16 14:55:55.047974

"""

# revision identifiers, used by Alembic.
revision = '418b3ff1c47'
down_revision = '29fa5a9b9555'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
