"""empty message

Revision ID: 421a3474d3e
Revises: 13079e2c6414
Create Date: 2015-01-05 13:39:23.946332

"""

# revision identifiers, used by Alembic.
revision = '421a3474d3e'
down_revision = '13079e2c6414'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
