"""empty message

Revision ID: 428d711f836b
Revises: 58bd06863fc2
Create Date: 2015-01-05 14:27:21.510875

"""

# revision identifiers, used by Alembic.
revision = '428d711f836b'
down_revision = '58bd06863fc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
