"""empty message

Revision ID: 44e7ae30d50
Revises: 68f069e7721
Create Date: 2015-01-14 16:18:41.502800

"""

# revision identifiers, used by Alembic.
revision = '44e7ae30d50'
down_revision = '68f069e7721'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
