"""empty message

Revision ID: 47a48d9528c6
Revises: 40c5c95b2a43
Create Date: 2015-01-15 12:15:05.651896

"""

# revision identifiers, used by Alembic.
revision = '47a48d9528c6'
down_revision = '40c5c95b2a43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
