"""empty message

Revision ID: 4ae7938fac71
Revises: 44e7ae30d50
Create Date: 2015-01-14 17:49:14.077254

"""

# revision identifiers, used by Alembic.
revision = '4ae7938fac71'
down_revision = '44e7ae30d50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tw_confirmed', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('tw_widget_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('tw_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tw_widget_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tw_widget_id')
    op.drop_column('users', 'tw_confirmed')
    op.drop_column('projects', 'tw_widget_id')
    op.drop_column('projects', 'tw_confirmed')
    ### end Alembic commands ###
