"""empty message

Revision ID: 4c1fe8a3daec
Revises: 369287a0c43b
Create Date: 2015-01-15 12:46:25.779695

"""

# revision identifiers, used by Alembic.
revision = '4c1fe8a3daec'
down_revision = '369287a0c43b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
