"""empty message

Revision ID: 4cef94517f8b
Revises: 1f94b813717d
Create Date: 2014-12-16 12:35:11.224978

"""

# revision identifiers, used by Alembic.
revision = '4cef94517f8b'
down_revision = '1f94b813717d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
