"""empty message

Revision ID: 4d289f3a6088
Revises: 19b6229b1977
Create Date: 2015-01-14 14:50:25.677490

"""

# revision identifiers, used by Alembic.
revision = '4d289f3a6088'
down_revision = '19b6229b1977'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
