"""empty message

Revision ID: 4da9b68f4918
Revises: 418b3ff1c47
Create Date: 2015-01-16 16:00:51.459544

"""

# revision identifiers, used by Alembic.
revision = '4da9b68f4918'
down_revision = '418b3ff1c47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
