"""empty message

Revision ID: 4e27891a33fc
Revises: 12cda8a4abf
Create Date: 2015-01-13 16:08:34.149739

"""

# revision identifiers, used by Alembic.
revision = '4e27891a33fc'
down_revision = '12cda8a4abf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
