"""empty message

Revision ID: 4f4b27fea9c4
Revises: 349210aa9b31
Create Date: 2015-01-05 12:50:02.450279

"""

# revision identifiers, used by Alembic.
revision = '4f4b27fea9c4'
down_revision = '349210aa9b31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
