"""empty message

Revision ID: 4ff2a7add324
Revises: 17ef808cbd0a
Create Date: 2015-02-10 15:27:31.329382

"""

# revision identifiers, used by Alembic.
revision = '4ff2a7add324'
down_revision = '17ef808cbd0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_2', 'species', [u'id'], unique=False)
    op.create_index('fkplantspecies', 'plant', [u'species_id'], unique=False)
    op.drop_table('page')
    op.drop_table('uploads')
    ### end Alembic commands ###
