"""empty message

Revision ID: 504f78fc2e9c
Revises: 13f4431f940b
Create Date: 2015-01-15 11:35:59.084598

"""

# revision identifiers, used by Alembic.
revision = '504f78fc2e9c'
down_revision = '13f4431f940b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me_html')
    ### end Alembic commands ###
