"""empty message

Revision ID: 5651f669806d
Revises: 248b1e88a76d
Create Date: 2015-01-05 13:44:52.786055

"""

# revision identifiers, used by Alembic.
revision = '5651f669806d'
down_revision = '248b1e88a76d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
