"""empty message

Revision ID: 573899ac4699
Revises: 31607810934a
Create Date: 2015-01-15 16:00:11.128610

"""

# revision identifiers, used by Alembic.
revision = '573899ac4699'
down_revision = '31607810934a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
