"""empty message

Revision ID: 58bd06863fc2
Revises: 5651f669806d
Create Date: 2015-01-05 14:27:06.334885

"""

# revision identifiers, used by Alembic.
revision = '58bd06863fc2'
down_revision = '5651f669806d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('project_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'project_name')
    ### end Alembic commands ###
