"""empty message

Revision ID: 5ae3430a492b
Revises: 3d6720c9c8a5
Create Date: 2015-01-05 13:32:37.707112

"""

# revision identifiers, used by Alembic.
revision = '5ae3430a492b'
down_revision = '3d6720c9c8a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('researcher_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'researcher_id')
    ### end Alembic commands ###
