"""empty message

Revision ID: 68f069e7721
Revises: 2fed564a5b0d
Create Date: 2015-01-14 16:18:32.544740

"""

# revision identifiers, used by Alembic.
revision = '68f069e7721'
down_revision = '2fed564a5b0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
