"""empty message

Revision ID: 93ff6e53f39
Revises: 34c3d83ddc25
Create Date: 2014-12-15 14:45:45.644706

"""

# revision identifiers, used by Alembic.
revision = '93ff6e53f39'
down_revision = '34c3d83ddc25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
