"""empty message

Revision ID: 9eb226546f
Revises: 1037c34cfdb0
Create Date: 2015-01-16 12:29:18.794463

"""

# revision identifiers, used by Alembic.
revision = '9eb226546f'
down_revision = '1037c34cfdb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
