"""empty message

Revision ID: d2568053d8e
Revises: 1e0293539f8c
Create Date: 2015-01-15 09:45:38.678216

"""

# revision identifiers, used by Alembic.
revision = 'd2568053d8e'
down_revision = '1e0293539f8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('other_researchers', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('tw_confirmed', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('tw_widget_id', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('twitter_name', sa.String(length=64), nullable=True))
    op.add_column('publications', sa.Column('other_researchers', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('tw_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tw_widget_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('twitter_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_name')
    op.drop_column('users', 'tw_widget_id')
    op.drop_column('users', 'tw_confirmed')
    op.drop_column('publications', 'other_researchers')
    op.drop_column('projects', 'twitter_name')
    op.drop_column('projects', 'tw_widget_id')
    op.drop_column('projects', 'tw_confirmed')
    op.drop_column('projects', 'other_researchers')
    ### end Alembic commands ###
