"""empty message

Revision ID: fc0c122460a
Revises: 11ac0ab909ac
Create Date: 2015-01-14 14:27:06.696684

"""

# revision identifiers, used by Alembic.
revision = 'fc0c122460a'
down_revision = '11ac0ab909ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
